/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as PlayersPesIdRouteImport } from './routes/players.$pesId'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as TournamentSlugRouteImport } from './routes/tournament.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPesIdRoute = PlayersPesIdRouteImport.update({
  id: '/$pesId',
  path: '/$pesId',
  getParentRoute: () => PlayersRoute,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentSlugRoute = TournamentSlugRouteImport.update({
  id: '/tournament/$slug',
  path: '/tournament/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/champions': typeof ChampionsRoute
  '/players': typeof PlayersRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/teams': typeof TeamsRoute
  '/tournaments': typeof TournamentsRoute
  '/players/$pesId': typeof PlayersPesIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/tournament/$slug': typeof TournamentSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/champions': typeof ChampionsRoute
  '/players': typeof PlayersRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/teams': typeof TeamsRoute
  '/tournaments': typeof TournamentsRoute
  '/players/$pesId': typeof PlayersPesIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/tournament/$slug': typeof TournamentSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/champions': typeof ChampionsRoute
  '/players': typeof PlayersRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/teams': typeof TeamsRoute
  '/tournaments': typeof TournamentsRoute
  '/players/$pesId': typeof PlayersPesIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/tournament/$slug': typeof TournamentSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/champions'
    | '/players'
    | '/rankings'
    | '/teams'
    | '/tournaments'
    | '/players/$pesId'
    | '/team/$teamId'
    | '/tournament/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/champions'
    | '/players'
    | '/rankings'
    | '/teams'
    | '/tournaments'
    | '/players/$pesId'
    | '/team/$teamId'
    | '/tournament/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/champions'
    | '/players'
    | '/rankings'
    | '/teams'
    | '/tournaments'
    | '/players/$pesId'
    | '/team/$teamId'
    | '/tournament/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChampionsRoute: typeof ChampionsRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  RankingsRoute: typeof RankingsRoute
  TeamsRoute: typeof TeamsRoute
  TournamentsRoute: typeof TournamentsRoute
  TeamTeamIdRoute: typeof TeamTeamIdRoute
  TournamentSlugRoute: typeof TournamentSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$pesId': {
      id: '/players/$pesId'
      path: '/$pesId'
      fullPath: '/players/$pesId'
      preLoaderRoute: typeof PlayersPesIdRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$slug': {
      id: '/tournament/$slug'
      path: '/tournament/$slug'
      fullPath: '/tournament/$slug'
      preLoaderRoute: typeof TournamentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlayersRouteChildren {
  PlayersPesIdRoute: typeof PlayersPesIdRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersPesIdRoute: PlayersPesIdRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChampionsRoute: ChampionsRoute,
  PlayersRoute: PlayersRouteWithChildren,
  RankingsRoute: RankingsRoute,
  TeamsRoute: TeamsRoute,
  TournamentsRoute: TournamentsRoute,
  TeamTeamIdRoute: TeamTeamIdRoute,
  TournamentSlugRoute: TournamentSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
